name: C++ CI Test Binary (Linux)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: (contains(github.event.head_commit.message, '[testbin]'))

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test selscan installation
      working-directory: bin/linux/
      run: |
        ./selscan --help
        ./norm --help

