name: C++ CI Test Binary
# This workflow will build and test the C++ code on windows using GitHub Actions.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    if: (contains(github.event.head_commit.message, '[testbin]'))

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Git credentials
      if: (contains(github.event.head_commit.message, '[binary_win]') || contains(github.event.head_commit.message, '[gsl]') )
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
   
    - name: Test selscan installation
    #   shell: msys2 {0}
      working-directory: bin/
      run: |
        selscan.exe --help
#./norm.exe --help

