name: C++ CI Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: (contains(github.event.head_commit.message, '[run ci]') || contains(github.event.head_commit.message, '[binary_linux]'))

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git credentials
      if: contains(github.event.head_commit.message, '[binary_linux]')
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          
    - name: Build selscan
      working-directory: src/
      run: make -f Makefile_linux -j

    - name: Test selscan installation
      working-directory: src/
      run: |
        ./selscan --help
        ./norm --help


    - name: Commit and push binary
      if: contains(github.event.head_commit.message, '[binary_linux]')
      run: |
        cp src/selscan bin/linux/
        cp src/norm bin/linux/
        git add bin/linux
        git commit -m "Adding bin to bin/linux" || echo "No changes to commit"
        git push

