name: C++ CI Mac
# This workflow will build and test the C++ code on macOS using GitHub Actions.

on:
  push:
    branches:
      - speedup
  pull_request:
    branches:
      - speedup

jobs:
  build:
    runs-on: macos-latest
    if: contains(github.event.head_commit.message, '[run ci]')

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: speedup

    - name: Build
      working-directory: src/
      run: make -f Makefile -j

    - name: Test
      working-directory: src/
      run: ./selscan --help
