name: C++ CI OSX # This workflow will build and test the C++ code on Intel-based macOS Runners using GitHub Actions. # Use macOS 13 (Ventura) for Intel-based Runners. These runners provide a 4-core Intel processor, 14 GB of RAM, and 14 GB of SSD storage. 

on:
  push:
      branches:
      - master
  pull_request:
      branches:
      - master

jobs:
    build:
      runs-on: macos-13
      if: (contains(github.event.head_commit.message, '[run ci]') || contains(github.event.head_commit.message, '[binary_osx]'))

      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git credentials
        if: contains(github.event.head_commit.message, '[binary_osx]')
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            
      - name: Build selscan
        working-directory: src/
        run: make -f Makefile_osx -j

      - name: Test selscan installation
        working-directory: src/
        run: |
          ./selscan --help
          ./norm --help

      - name: Commit and push binary
        if: contains(github.event.head_commit.message, '[binary_osx]')
        run: |
            cp src/selscan bin/osx/
            cp src/norm bin/osx/
            git add bin/osx
            git commit -m "Adding bin to bin/osx" || echo "No changes to commit"
            git push

        