name: C++ CI Windows
# This workflow will build and test the C++ code on windows using GitHub Actions.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    # if: contains(github.event.head_commit.message, '[run ci]')

    steps:

    - name: Configure Git to Handle Line Endings
      run: git config --global core.autocrlf input

    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set Up MSYS2 Environment
    #   uses: msys2/setup-msys2@v2
    #   with:
    #     msystem: MINGW64
    #     update: true
    #     install: >-
    #       mingw-w64-x86_64-toolchain
    #       base-devel
    #       mingw-w64-x86_64-gcc
    #       mingw-w64-x86_64-winpthreads-git
    - name: Set up MinGW-w64
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        
    - name: Verify make Installation
      run: which make
      shell: msys2 {0}

    - name: Build
      shell: msys2 {0}
      working-directory: src/
      run: make -f Makefile_win -j

    - name: Test
      shell: msys2 {0}
      working-directory: src/
      run: ./selscan --help


      