name: C++ CI Windows
# This workflow will build and test the C++ code on windows using GitHub Actions.

on:
  push:
    branches:
      - speedup
  pull_request:
    branches:
      - speedup

jobs:
  build:
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, '[run ci]')

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set Up MSVC Environment ## works
    #   uses: ilammy/msvc-dev-cmd@v1

    - name: Set Up MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: clang64
        update: true
        install: >-
          git
          base-devel
          mingw-w64-clang-x86_64-toolchain
       
    - name: Verify GCC/Clang Installation
      run: gcc --version; clang++ --version

    - name: Build Project
      shell: msys2 {0}
      working-directory: src/
      run: make -f Makefile_win
#      shell: bash

    - name: Test
      shell: msys2 {0}
      working-directory: src/
      run: ./selscan.exe --help
