name: C++ CI Windows
# This workflow will build and test the C++ code on windows using GitHub Actions.

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    # if: contains(github.event.head_commit.message, '[run ci]')

    steps:

    - name: Configure Git to Handle Line Endings
      run: git config --global core.autocrlf input

    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set Up MSYS2 Environment
    #   uses: msys2/setup-msys2@v2
    #   with:
    #     msystem: MINGW64
    #     update: true
    #     install: >-
    #       mingw-w64-x86_64-toolchain
    #       base-devel
    #       mingw-w64-x86_64-gcc
    #       mingw-w64-x86_64-winpthreads-git


    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
  # mingw-w64-x86_64-cmake
  # mingw-w64-x86_64-ninja

    - name: Configure PATH
      run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

  #     - name: Install Make
  # run: pacman -S --noconfirm mingw-w64-x86_64-make

    # - name: Verify make Installation
    #   run: which make
    #   shell: msys2 {0}

    - name: Build
      shell: msys2 {0}
      working-directory: src/
      run: mingw32-make -f Makefile_win

    - name: Test
      shell: msys2 {0}
      working-directory: src/
      run: ./selscan --help


      