name: C++ CI Windows
# This workflow will build and test the C++ code on windows using GitHub Actions.

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    # if: contains(github.event.head_commit.message, '[run ci]')

    steps:

    - name: Configure Git to Handle Line Endings
      run: git config --global core.autocrlf input


    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: speedup

    # - name: Set Up MSYS2
    #   uses: msys2/setup-msys2@v2
    #   with:
    #     msystem: MINGW64
    #     install: >-
    #       mingw-w64-x86_64-gcc
    #       make
    #     update: true

    - name: Set Up MSYS2 Environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-winpthreads-git
    # mingw-w64-x86_64-pthreads

    - name: Add MSYS2 MinGW64 to PATH
      run: echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append



    # - name: Install Dependencies
    #     shell: msys2 {0}
    #     run: pacman -Syu --noconfirm zlib zlib-devel

    - name: Build
      shell: msys2 {0}
      working-directory: src/
      run: make -f Makefile_win -j

    - name: Test
      shell: msys2 {0}
      working-directory: src/
      run: ./selscan --help


      